decision_logs:
  console: true
plugins:
  envoy_ext_authz_grpc:
    addr: ":9191"
    path: envoy/authz/allow
    oidc-config:
      callback-url: http://localhost:8080/oidc/callback
      realms:
      - name: tenantA
        login-url: http://localhost/auth/tenantA
        client-id: opa-oidc
        client-secret: s3cr37.A
      - name: tenantB
        login-url: http://localhost/auth/tenantB
        client-id: opa-oidc
        client-secret: s3cr37.B
